blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/durellwilson/security-awareness-course/security
    about: Report security issues privately
  - name: Community Discussion
    url: https://github.com/durellwilson/security-awareness-course/discussions
    about: Ask questions and discuss topics
